[Network]
  host = "localhost"
  port = 25565
  compression-threshold = 256 # Disable = -1

[Motd]
  motd = "                   &bGo Server &3[1.8] \n                       &fJoin &lNow&f"
  favicon = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAALVBMVEUArdj///8Ap9Xc9PouvN+p5PJCwuKY3vCB1+y96vUattzr+fzM7/hs0OlYyebbfcnGAAACLElEQVRIx2IYBaOAAsCkpABhKOFQ4NdxDayO5V2WAjb5TEFBwWNAmdSNgoIhWFSwC4LAJQZWMP0I1W4loO0TwRJiWoZgWg7ZCLa0tLRXqoKCwnMEBaV5oPQCJAOWl5eXBzwUFLzAkC1T1igo/YDBWVCwCS7PleYCBAyGgmIKSgqLFAQFdykwqAgKToAr0J0aCgRsID0dHR2dYPcxBQoaIKxQYGJx8dIQFHTQBToOYjtTIUgBAnjOPKEuKLiAG6xABiQSKHgALRSACpyyja1BJoDcJShYhKZAAyy0GBJWDJyCgkloCoCOlGBgMRSUFBSUZWA5KCiJEdIHBQV3AnEAMCIsgbQIhgLAHCEuZHoIohA2IIAaWHwCA8SvJpixybQUKH4OSHsCaQsc6eUJEzTdMGFVAIxzWOxjJjquBVwOLUj85+gKuA85TipRYAAbDTRHTdYD3ZOHCm8FlNtpHGU57BG6ZqqP7MEGVC9cDpucayA7PfFhcsnqWUcvMlftQPNjeMxl1pJNc4vrHJkcGQReaifsQguIfXuyGV8cECl+srDtNpeExEI2WTQ3dLXksq97UMA+T3deLsPVrmyGcjQFCmAfKDABIdBCNXEFJbyZlK+BUC5WYKAfMCYAGAQJADQFs4E4FI+CberAjMvgjVOBMBcrMPPYaOJWUAksQwzurcZthSRQgaxSIX4FARGceBUcfCDIi0eBuqjqJC8e3Aqkm4UvS944iKYAE1BXAQDVEZ601fol4QAAAABJRU5ErkJggg=="
  max = 100
  online = 0

[Game]
  default-world = "world"
  send-players = true
  online-mode = true
  debug-packets = true